name: 检查API可用性

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 0点运行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许写入仓库内容

jobs:
  check-apis:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          # 安装必要依赖，添加urllib3解决SSL警告
          pip install requests base58 urllib3
          # 禁用SSL警告（避免脚本输出被警告淹没）
          python -c "import urllib3; urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)"
      
      - name: 运行API检查脚本
        run: python check_apis.py
      
      - name: 提交所有更新的文件
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "自动更新API配置文件 $(date +'%Y-%m-%d')" || echo "没有需要提交的更改"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
